inherit_from: configs/NARUTO/NARUTO_coslam.yaml
mapping:
  bound: [[-2.6, 2.6],[-2.6,2.6],[-2.6,2.6]]
  marching_cubes_bound: [[-0.65,0.75],[-0.5,0.9],[-1.4, 1.65]]
  

data:
  trainskip: 1

mesh:
  resolution: 512
  render_color: False
  vis: 500
  voxel_eval: 0.01
  voxel_final: 0.005
  visualisation: False